### ISSUE TITLE
/etc/phoronix-test-suite.xml is overwritten on every start

### ISSUE THREAD

**Issue by albgus** [phoronix-test-suite/phoronix-test-suite#382]
Hello,

I have installed PTS 9.0.1 with the .deb file referenced on http://www.phoronix-test-suite.com/

Then I have configured some settings, such as port number, proxy settings and anonymous reporting in /etc/phoronix-test-suite.xml

However, when I start phoromatic-server with the included systemd unit, the configuration file is overwritten, returning all settings to their default.

**Comment by michaellarabel** [comment]
Hi @albgus, the file shouldn't overwrite the values assuming your XML isn't malformed. Can you post your configured configuration file that ultimately gets overwritten?

**Comment by albgus** [comment]
Some further digging revealed that the phoromatic server fails to start because the php-sqlite package was not present. Although the result viewer was still able to start on a random which was throwing me off a bit.

After installing php-sqlite it works as expected, but it still seems like a bug that the configuration is reset because of a missing package.

**Comment by michaellarabel** [comment]
Hmmm thanks for that tid-bit. Will try to reproduce if the Phoromatic Server resets the config file when php-sqlite isn't present, but at least off the top of my head not sure how that would happen, but will look into it. Thanks.

**Comment by albgus** [comment]
For what it's worth, I encountered this on a freshly installed Ubuntu 18.04 machine and installed PTS with the following ansible play.

```yaml
---

- hosts: master
  become: yes
  tasks:
    - name: Download installer package
      get_url:
        url: "http://phoronix-test-suite.com/releases/repo/pts.debian/files/phoronix-test-suite_9.0.1_all.deb"
        dest: /tmp/pts.deb
      environment:
        http_proxy: "http://www-proxy.example.com:8080"
    - name: Install main package
      apt:
        deb: /tmp/pts.deb
    - name: Copy configuration
      copy:
        src: files/phoronix-test-suite-server.xml
        dest: /etc/phoronix-test-suite.xml
        mode: 0664
        owner: root
    - name: reload systemd
      command: systemctl daemon-reload
    - name: Start service
      service:
        name: phoromatic-server
        state: started
        enabled: yes
```

I could see the following output in the syslog 

```
Oct 23 15:40:17 pts-master systemd[1]: Started Phoronix Test Suite Phoromatic Server.
Oct 23 15:40:17 pts-master phoronix-test-suite[12067]: Port 8134 chosen as random port for this instance. Change the default port via the Phoronix Test Suite user configuration file.
Oct 23 15:40:17 pts-master phoronix-test-suite[12067]: PHP SQLite3 support must first be enabled before accessing the Phoromatic server (e.g. installing the php-sqlite or php-pdo package depending on the distribution).
```
